version: "3.9"
services:
  api:
    build: ../apps/api
    env_file: ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../apps/api:/app
      - ../data:/data
    environment:
      - WORKER_URL=http://worker:8001
  worker:
    build: ../apps/worker
    env_file: ../.env
    volumes:
      - ../apps/worker:/app
      - ../data:/data
  ui:
    build: ../apps/ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ../apps/ui:/app
      - /app/node_modules
